3548:   committed patch 1777220 by John Faith to fix compilation of Inkscape on OS X 10.3 (Panther)
  g_return_val_if_fail(fabs(denom) > 1e-6, NR::Nothing());

  is apparently causing gcc 3.3 to fail (OS X 10.3) with the error:

  line-geometry.cpp: In member function `virtual NR::Maybe<NR::Point>
  Box3D::Line::intersect(const Box3D::Line&)':
  line-geometry.cpp:57: error: parse error before `;' token

  If the NR::Nothing() is simply broken out as its own variable instead of
  including it in g_return_val_if_fail(), then the file compiles. The root
  cause is not known, but I assume this is a gcc bug.

  This was the only source change needed for building svn 15634 for OS X
  10.3.